package game_play;

import files_package.FileOperations;
import javax.swing.*;

public class PlayFrame extends javax.swing.JFrame {

     private String category;

     /**
      * Creates new form PlayFrame
      */
     public PlayFrame() {
          setContentPane(new JLabel(new ImageIcon("Background2.png")));
          initComponents();
          categorylabel.setBackground(new java.awt.Color(0, 0, 0, 1));
          setBounds(400, 200, 505, 350);
     }

     public String getCategory() {
          return category;
     }

     public void setCategory(String category) {
          this.category = category;
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MoviesRadioButton = new javax.swing.JRadioButton();
        AnimeRadioButton = new javax.swing.JRadioButton();
        CountriesRadioButton = new javax.swing.JRadioButton();
        FoodRadioButton = new javax.swing.JRadioButton();
        HistoryRadioButton = new javax.swing.JRadioButton();
        NamesRadioButton = new javax.swing.JRadioButton();
        BackButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();
        categorylabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        buttonGroup1.add(MoviesRadioButton);
        MoviesRadioButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MoviesRadioButton.setForeground(new java.awt.Color(0, 0, 153));
        MoviesRadioButton.setText("Movies");
        MoviesRadioButton.setBorder(null);
        MoviesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoviesRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MoviesRadioButton);
        MoviesRadioButton.setBounds(80, 90, 110, 20);

        buttonGroup1.add(AnimeRadioButton);
        AnimeRadioButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AnimeRadioButton.setForeground(new java.awt.Color(0, 0, 153));
        AnimeRadioButton.setText("Anime");
        AnimeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimeRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AnimeRadioButton);
        AnimeRadioButton.setBounds(210, 90, 100, 20);

        buttonGroup1.add(CountriesRadioButton);
        CountriesRadioButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CountriesRadioButton.setForeground(new java.awt.Color(0, 0, 153));
        CountriesRadioButton.setText("Countries");
        CountriesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountriesRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CountriesRadioButton);
        CountriesRadioButton.setBounds(80, 130, 110, 20);

        buttonGroup1.add(FoodRadioButton);
        FoodRadioButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        FoodRadioButton.setForeground(new java.awt.Color(0, 0, 153));
        FoodRadioButton.setText("Food");
        FoodRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(FoodRadioButton);
        FoodRadioButton.setBounds(210, 130, 80, 20);

        buttonGroup1.add(HistoryRadioButton);
        HistoryRadioButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        HistoryRadioButton.setForeground(new java.awt.Color(0, 0, 153));
        HistoryRadioButton.setText("History");
        HistoryRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HistoryRadioButton);
        HistoryRadioButton.setBounds(80, 170, 90, 20);

        buttonGroup1.add(NamesRadioButton);
        NamesRadioButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NamesRadioButton.setForeground(new java.awt.Color(0, 0, 153));
        NamesRadioButton.setText("Names");
        NamesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamesRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NamesRadioButton);
        NamesRadioButton.setBounds(210, 170, 90, 20);

        BackButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BackButton.setForeground(new java.awt.Color(0, 0, 153));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(420, 280, 61, 23);

        PlayButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PlayButton.setForeground(new java.awt.Color(0, 0, 153));
        PlayButton.setText("Play");
        PlayButton.setMaximumSize(new java.awt.Dimension(75, 25));
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PlayButton);
        PlayButton.setBounds(160, 210, 61, 25);

        categorylabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        categorylabel.setForeground(new java.awt.Color(0, 0, 153));
        categorylabel.setText("Choose a category:");
        getContentPane().add(categorylabel);
        categorylabel.setBounds(80, 40, 240, 40);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setText("How to play");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(313, 280, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
         setVisible(false);
         WelcomeScreen JFrame = new WelcomeScreen(null);
         JFrame.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void MoviesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoviesRadioButtonActionPerformed
         setCategory("Movies");
    }//GEN-LAST:event_MoviesRadioButtonActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed

         if (MoviesRadioButton.isSelected()) {
              setCategory("Movies");
         } else if (AnimeRadioButton.isSelected()) {
              setCategory("Anime");
         } else if (CountriesRadioButton.isSelected()) {
              setCategory("Countries");
         } else if (FoodRadioButton.isSelected()) {
              setCategory("Food");
         } else if (HistoryRadioButton.isSelected()) {
              setCategory("History");
         } else if (NamesRadioButton.isSelected()) {
              setCategory("Names");
         }
         if (MoviesRadioButton.isSelected() || AnimeRadioButton.isSelected() || CountriesRadioButton.isSelected() || FoodRadioButton.isSelected()
                 || HistoryRadioButton.isSelected() || NamesRadioButton.isSelected()) {
              setVisible(false);
              //this.dispose();
//            SceneFrame sceneFrame = new SceneFrame(getCategory());
//            sceneFrame.setVisible(true);
              game_play.SceneFrame.word = FileOperations.fileReader(getCategory());
              game_play.SceneFrame.main(null);
         } else {
              JOptionPane.showMessageDialog(new WelcomeScreen(null), "Please choose a category!", "Error", JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void AnimeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimeRadioButtonActionPerformed
         ///
    }//GEN-LAST:event_AnimeRadioButtonActionPerformed

    private void CountriesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountriesRadioButtonActionPerformed
         ////
    }//GEN-LAST:event_CountriesRadioButtonActionPerformed

    private void FoodRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodRadioButtonActionPerformed
         ///
    }//GEN-LAST:event_FoodRadioButtonActionPerformed

    private void HistoryRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryRadioButtonActionPerformed
         ///
    }//GEN-LAST:event_HistoryRadioButtonActionPerformed

    private void NamesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamesRadioButtonActionPerformed
         ////
    }//GEN-LAST:event_NamesRadioButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Choose a category then click play.");
        JOptionPane.showMessageDialog(this, "Given a scene, You are supposed to find a number (1, 2, 3) and click it.");
        JOptionPane.showMessageDialog(this, "Every click shows you a hidden word. You lose if you click 3 times a different spot or if the time is out");
    }//GEN-LAST:event_jButton1ActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
           * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(PlayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>
          
        //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(() -> {
               new PlayFrame().setVisible(true);
          });
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AnimeRadioButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JRadioButton CountriesRadioButton;
    private javax.swing.JRadioButton FoodRadioButton;
    private javax.swing.JRadioButton HistoryRadioButton;
    private javax.swing.JRadioButton MoviesRadioButton;
    private javax.swing.JRadioButton NamesRadioButton;
    private javax.swing.JButton PlayButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel categorylabel;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
